# Generated by Django 5.0.3 on 2024-03-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_contact_alter_posts_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
