# Generated by Django 5.0.3 on 2024-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
