# Generated by Django 5.0.3 on 2024-03-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='users/images/default_profile_pic.png', upload_to='users/images/'),
        ),
    ]
