# Generated by Django 5.0.3 on 2024-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='default_profile_pic.png', upload_to='users/images/'),
        ),
    ]
